ls:
  .dir: kebab-case
  .md: kebab-case | regex:[0-9A-Z\-]+
  .html: kebab-case
  .css: kebab-case
  .jpg: kebab-case
  .jpeg: kebab-case
  .svg: kebab-case
  .gif: kebab-case
  .mp4: kebab-case
  .ico: kebab-case
  .js: kebab-case
  .jsx: PascalCase

ignore:
  - .git
  - node_modules
  - accessibility_report
  - .github
  - .vscode
